language: php
dist: trusty
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

install:
  - composer self-update
  - composer install --dev --no-interaction

allowed_failures:
  - nightly

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls
